name: move assigned issue to in progress

on:
  issues:
    types: [assigned]
    
jobs:
  move_card:
    runs-on: ubuntu-latest
    steps:
      - uses: HiromiShikata/gh-actions-move-all-cards-on-projects@v1.0.2
        with:
          project_name: 8
          from_column_name: Backlog
          to_column_name: In Progress
          github_token: ${{ secrets.GITHUB_TOKEN }}
