name: In Progress Change
on:
  issues:
    types: [assigned]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["Status: Backlog"]
            })
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["Status: In Progress"]
            })
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          organization: layars
          project_number: 8
          content_id: ${{ github.event.client_payload.command.resource.id }}
          field: Status
          value: "In Progress"
