name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@0.8.3
        with:
          project: 8
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
