name: Releases
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: install
      run: pnpm ci:install
    
    - name: build
      run: pnpm build

    - name: Setup npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

    - name: Create Release Pull Request
      uses: changesets/action@v1
      with:
        version: pnpm ci:version
        commit: "chore: update versions"
        title: "chore: update versions"
        publish: pnpm ci:publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}