name: layars-tokens
on:
  pull_request:
    types: [opened, reopened]
  push:
    paths:
      - packages/layars-tokens/**

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: install
      run: pnpm install
    - name: build
      run: pnpm --filter @layars/tokens build
    - name: test
      run: pnpm --filter @layars/tokens test
